---
#title: "cv_quang"
format: html
editor: visual
---

::: {style="text-align:center; font-size:30px;"}
<strong>Quang Pham</strong>
:::

::: {style="text-align:center"}
215 Tower Road, Ithaca, NY 14850

949-317-7551 \| qnp3\@cornell.edu \| github.com/qphamhub \| Linkedin
:::

### Education

::::: {style="display: flex; justify-content: space-between;"}
::: {style="flex: 1;"}
**Cornell University**, *PhD in Ecology & Evolutionary Biology*</em>
:::

::: {style="flex: 0 0 200px; text-align: right;"}
Ithaca, NY
:::
:::::

:::::::::::::::: {style="display: flex; justify-content: space-between;"}
::::::::::::::: {style="flex: 1;"}
-   GPA: 4.0/4.0, Cornell Fellowship (2024)

    </div>

    ::: {style="flex: 0 0 200px; text-align: right;"}
    2024–Present
    :::

    </div>

:::::::::::::: {style="display: flex; justify-content: space-between;"}
::::::::::::: {style="flex: 1;"}
-   Relevant courses: Entrepreneurship for Scientists & Engineers

    </div>

    ::: {style="flex: 0 0 200px;"}
    :::

    </div>

::::: {style="display: flex; justify-content: space-between;"}
::: {style="flex: 1;"}
**Soka University of America**, *BA in Life Sciences*</em>
:::

::: {style="flex: 0 0 200px; text-align: right;"}
Aliso Viejo, CA
:::
:::::

::::::::: {style="display: flex; justify-content: space-between;"}
:::::::: {style="flex: 1;"}
-   GPA: 3.8/4.0, magna cum laude, full ride scholarship

    </div>

    ::: {style="flex: 0 0 200px; text-align: right;"}
    2020–2024
    :::

    </div>

### Professional Experience

::::: {style="display: flex; justify-content: space-between;"}
::: {style="flex: 1;"}
**Graduate Researcher**, *Cornell University*, Ithaca, NY</em>
:::

::: {style="flex: 0 0 200px; text-align: right;"}
08/2024-Present
:::
:::::

::: {.content-visible .when-format-html style="text-align:right;"}
-   Develop experiments and integrate techniques in morphology, genomics, transcriptomics, and microbiomics to identify skin evolution and development pathways in amphibians
:::

::: {.content-visible .when-format-html style="text-align:right;"}
-   Publish findings in peer-reviewed studies and present at conferences

 **Consultant**, *Cornell Graduate Consulting Club*, Ithaca, NY [2025-Present]{style="float:right"} 

- Perform due diligence and define the business model of a local charity-giving platform []{style="float:right"}

:::

### Leadership & Outreach

### Skills & Interests
::::::::
:::::::::
:::::::::::::
::::::::::::::
:::::::::::::::
::::::::::::::::
